### ISSUE TITLE
undefined method `option' for Librarian::Cli:Class when trying to do bundle console

### ISSUE THREAD

**Issue by ThomasAlxDmy** [applicationsonline/librarian#143] opened 2013-05-04 04:42 UTC
Hi guys here the issue I'm facing when doing bundle console:

bundle console

/Users/.rvm/gems/ruby-1.9.2-p320@api/gems/librarian-0.1.0/lib/librarian/cli.rb:71:in class:Cli': undefined methodoption' for Librarian::Cli:Class (NoMethodError)
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/librarian-0.1.0/lib/librarian/cli.rb:10:in module:Librarian'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/librarian-0.1.0/lib/librarian/cli.rb:9:in'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/backports-2.6.7/lib/backports/tools.rb:314:in require'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/backports-2.6.7/lib/backports/tools.rb:314:inrequire_with_backports'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/librarian-chef-0.0.1/lib/librarian/chef/cli.rb:3:in <top (required)>'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/backports-2.6.7/lib/backports/tools.rb:314:inrequire'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/backports-2.6.7/lib/backports/tools.rb:314:in require_with_backports'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/soloist-1.0.1/lib/soloist/cli.rb:1:in'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/backports-2.6.7/lib/backports/tools.rb:314:in require'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/backports-2.6.7/lib/backports/tools.rb:314:inrequire_with_backports'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/soloist-1.0.1/lib/soloist.rb:2:in <top (required)>'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:inrequire'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/runtime.rb:68:in block (2 levels) in require'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:ineach'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/runtime.rb:66:in block in require'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:ineach'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/runtime.rb:55:in require'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler.rb:119:inrequire'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/cli.rb:493:in console'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/vendor/thor/task.rb:22:inrun'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/vendor/thor/invocation.rb:118:in invoke_task'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/vendor/thor.rb:263:indispatch'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/lib/bundler/vendor/thor/base.rb:386:in start'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/gems/bundler-1.1.3/bin/bundle:13:in'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/bin/bundle:19:in load'
from /Users/.rvm/gems/ruby-1.9.2-p320@api/bin/bundle:19:in'
Thomas:$ bundle config

Any idea why this is raising?

**Comment by yfeldblum** [comment] 2013-06-30 18:38
- `options` comes from the gem `thor`.
- Cannot reproduce.

**Comment by yfeldblum** [comment] 2013-12-16 05:45
Closing because old.

**Closed as completed by yfeldblum** 2013-12-16 05:45 UTC
