### ISSUE TITLE
Chef: Git Discovery Support

### ISSUE THREAD

**Issue by techtonik** [applicationsonline/librarian#84] opened 2012-06-23 08:36 UTC
```
site "https://github.com/opscode-cookbooks/"

cookbook "vim"
```

Right now it is:

```
$ librarian-chef install
Could not get https://github.com/opscode-cookbooks//cookbooks/vim because 400 Bad Request!
```

Fallback with Git detector can make this working.

**Comment by yfeldblum** [comment] 2012-06-23 16:02
Duplicate of #40.

**Closed as completed by yfeldblum** 2012-06-23 16:02 UTC

**Comment by techtonik** [comment] 2012-06-24 14:34
This one is not github specific and is not about using GitHub API at all.

**Comment by yfeldblum** [comment] 2012-06-24 15:03
See the discussion towards the end. The idea of a `git_site` source.

**Comment by techtonik** [comment] 2012-06-24 21:43
I don't get that discussion and how to fit my user story there. #40 seems too high level and abstract. You probably don't want me to highjack it and minify to this single use case with Git. I don't get why `site "https://github.com/opscode-cookbooks/"` is impossible to implement.

**Comment by yfeldblum** [comment] 2012-06-24 22:21
My suggestion, which emerged in the discussion in #40, is to support the following source declarations:

```
git_site "https://github.com/opscode-cookbooks"
git_site "opscode-cookbooks" # shorthand for the above

git_site "https://github.com/cookbooks"
git_site "cookbooks" # likewise
```

And every other such case as well, and not limited to Github.

Your suggestion is a particular instance of the general case from the discussion in #40. If I'm going to support this particular case, then of course I'm actually going to support the general case instead, and the particular case will naturally be supported through the general case.

**Comment by till** [comment] 2012-08-03 14:28
@yfeldblum I think your example doesn't make sense since the format is `github.com/user/repo` and your's is `github.com/repo`.

I agree that this is needed, I hacked it into my Cheffile:

```
require "git"

temp_dir     = "#{::Dir.tmpdir}/librarian-easybib/"
default_repo = "https://github.com/till/easybib-cookbooks"

if !::File.directory?(temp_dir)
  ::FileUtils.mkdir_p temp_dir
end

if !::File.directory?("#{temp_dir}/.git")
  Git.clone(default_repo, temp_dir)
else
  repo = Git.open(temp_dir)
  repo.pull('origin', 'master') # this doesn't seem to work, no idea why
end

Dir["#{temp_dir}/*/"].map { |a|
  cookbook_name = ::File.basename(a)
  cookbook cookbook_name,
    :path => temp_dir
}
```

**Comment by till** [comment] 2012-08-03 14:30
I have no preference – `site` vs. `git_site`. I'd just like to use it. ;)
